spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book
    username: mfuras
    password: mfuras
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8070

application:
  config:
    customer-url: http://localhost:8222/api/v1/customers
    branch-url: http://localhost:8222/api/v1/branch
    product-url: http://localhost:8222/api/v1/products
