spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/bookings
    username: mfuras
    password: mfuras
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: bookingsConfirmation:com.mfuras.booking.kafka.BookingsConfirmation;
server:
  port: 8070

application:
  config:
    customer-url: http://customer:8090/api/v1/customers
    branch-url: http://branch:8060/api/v1/branches
