spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb:http://customer-service
          predicates:
              - Path=/api/v1/customers/**
        - id: bookings-service
          uri: lb:http://bookings-service
          predicates:
            - Path=/api/v1/bookings/**
        - id: product-service
          uri: lb:http://product-service
          predicates:
            - Path=/api/v1/products/**
server:
  port: 8222