spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: notification_db
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: bookingGroup,branchGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: bookingConfirmation:com.mfuras.booking.kafka.BookingConfirmation,branchConfirmation:com.mfuras.booking.notification.BranchNotificationRequest
  mail:
    host: mail-dev
    port: 1025
    username: mfuras
    password: mfuras
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

server:
  port: 8040