spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb:http://CUSTOMER-SERVICE
          predicates:
              - Path=/api/v1/customers/**
        - id: bookings-service
          uri: lb:http://BOOKINGS-SERVICE/
          predicates:
            - Path=/api/v1/bookings/**
        - id: branch-service
          uri: lb:http://BRANCH-SERVICE
          predicates:
            - Path=/api/v1/branch/**
server:
  port: 8222